version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      # - chmod +x bash_npm_install.sh
      # - ./bash_npm_install.sh
      - aws cloudformation package --template-file src/cloudformation/api/template.yml --s3-bucket $STCAuthBucket --output-template-file packaged-template.yml
      - aws s3 cp src/spec/openapi.yml "s3://$STCAuthBucket"
artifacts:
  files:
    - packaged-template.yml
